POST http://localhost:3000/categorias/crear HTTP/1.1
content-type: application/json

{
    "nombre": "Perdon",
    "descripcion": "sin descripcion"
}

###
GET http://localhost:3000/categorias HTTP/1.1

###
GET http://localhost:3000/categorias/mostrar/6015d5c5897854241037ad8b HTTP/1.1

###
PUT http://localhost:3000/categorias/editar/6015d5c5897854241037ad8b HTTP/1.1
content-type: application/json

{
    "nombre": "Santidad",
    "descripcion": "Versiculos relacionados con la santidad"
}

###
GET http://localhost:3000/categorias/editar/6015d5c5897854241037ad8b HTTP/1.1

###
DELETE http://localhost:3000/categorias/eliminar/6015d5c5897854241037ad8bculo HTTP/1.1
content-type: application/json
###
POST http://localhost:3000/versiculos/crear HTTP/1.1
content-type: application/json

{
    "cita": {"libro": "Salmos", "capitulo":1,"versiculoInicial":1,"versiculoFinal":3},
    "texto": "Bienaventurado el varón que no anduvo en consejo de malos, Ni estuvo en camino de pecadores, Ni en silla de escarnecedores se ha sentado; Sino que en la ley de Jehová está su delicia, Y en su ley medita de día y de noche. Será como árbol plantado junto a corrientes de aguas,Que da su fruto en su tiempo,Y su hoja no cae; Y todo lo que hace, prosperará.",
    "comentario": "sin descripcion"
}

###
{
    "cita": {"libro": "Genesis", "capitulo":1,"versiculoInicial":1,"versiculoFinal":1},
    "texto": "En el principio creo Dios los cielos y la tierra",
    "comentario": "sin descripcion"
}

###
GET http://localhost:3000/versiculos HTTP/1.1

###
GET http://localhost:3000/versiculos/mostrar/6015dffd96e8b84da89ab50a HTTP/1.1

###
PUT http://localhost:3000/versiculos/editar/6015d5c5897854241037ad8b HTTP/1.1
content-type: application/json

{
    "comentario": "Santidad"
}

###
GET http://localhost:3000/versiculos/editar/6015d5c5897854241037ad8b HTTP/1.1

###
DELETE http://localhost:3000/versiculos/eliminar/6015d5c5897854241037ad8b HTTP/1.1
###

POST http://localhost:3000/usuarios/registro HTTP/1.1
content-type: application/json

{
    "nombre": "Eliana Chavez",
    "correo": "elianachavezv@outlook.com",
    "contrasena": "ContraseñaPrueba",
    "confirmacion": "ContraseñaPrueba8"
}

    